### ISSUE TITLE
Which rules do the validator satisfy really?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/conll-workbench#15]
I assume a conll representation cannot be empty and it must have a root. But what else is already coded up in the rules? For UD we know it should be a dag, but this doesn't need to be the case for other versions of CoNLL. are we validating UD and SD? UD v1.0 or UD v2.0?

**Comment by arademaker** [comment]
@vcvpaiva na versão atual, nossa validação basicamente consiste em chamar o validate.py de https://github.com/universaldependencies/tools. Vide 

https://github.com/own-pt/conll-workbench/blob/master/validator/conll-validator.lisp#L17-L18

Logo estamos valisando conllu, UD 2.0.
