### ISSUE TITLE
aux:pass

### ISSUE THREAD

**Issue by arademaker** [own-pt/conll-workbench#2]
http://universaldependencies.org/u/dep/aux_.html

mas 

```
[Line                   28]: Unknown UD DEPREL: aux:pass
[Line                   143]: Unknown UD DEPREL: aux:pass
[Line                   223]: Unknown UD DEPREL: aux:pass
*** FAILED *** with 3 errors
Syntax errors: 3
```

**Comment by fcbr** [comment]
Need to update https://github.com/UniversalDependencies/tools/tree/master/data

**Comment by fcbr** [comment]
Please report this to the `tools` project (or maybe submit a pull request fixing the issue.)

**Comment by arademaker** [comment]
solved with https://github.com/UniversalDependencies/tools/commit/a75c3e4f9bf1861d7dfce0e337c88d1b65ce554e
